**Write a program which takes two digits m (row) and n (column) as input and generates a two-dimensional array. The element value in the $i^{th}$ row and $j^{th}$ column of the array should be $i * j$.**

In [1]:
import numpy as np

row = int(input("Number of rows: "))
col = int(input("Number of columns: "))
matrix = [[c for c in range(col)] for r in range(row)]

for i in range(row):
    for j in range(col):
        matrix[i][j] = i * j

print (np.array(matrix).reshape(row, col))

Number of rows: 3
Number of columns: 4
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


**OR**

In [1]:
row = int(input("Number of rows: "))
col = int(input("Number of columns: "))
matrix = [[c for c in range(col)] for r in range(row)]

for i in range(row):
    for j in range(col):
        matrix[i][j] = i * j
        
print (matrix)

Number of rows: 3
Number of columns: 4
[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]
