**Write a Python program which takes two digits m (row) and n (column) as input and generates a two-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.** <br/>
Note : <br/>
i = 0,1.., m-1 <br/>
j = 0,1, n-1. <br/>

Test Data : Rows = 3, Columns = 4 <br/>
Expected Result : 

[[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 4, 6]]

In [1]:
row = int(input('Number of rows: '))
col = int(input('Number of columns: '))
matrix = [[c for c in range(col)] for r in range(row)]

for i in range(row):
    for j in range(col):
        matrix[i][j] = i * j

import numpy as np

print (np.array(matrix).reshape(row, col))

Number of rows: 3
Number of columns: 4
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]


**Write a Python program that accepts a sequence of lines (blank line to terminate) as input and prints the lines as output (all characters in lower case).**

In [1]:
l = []

while True:
    lines = input()
    if lines:
        l.append(lines.lower())
    
    else:
        break
        
for i in l:
    print (i)

Today is 13th March 2022

today is 13th march 2022
